-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 22:58:08 2017
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virtuagym` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `virtuagym` ;

-- -----------------------------------------------------
-- Table `virtuagym`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuagym`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `date_joined` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuagym`.`workouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuagym`.`workouts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL COMMENT 'descriptive details about the plan describing affected muscle groups etc',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuagym`.`muscle_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuagym`.`muscle_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virtuagym`.`exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuagym`.`exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exercise_name` VARCHAR(45) NULL,
  `muscle_group_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `muscle_group_id_idx` (`muscle_group_id` ASC),
  CONSTRAINT `fk_muscle_group_id`
    FOREIGN KEY (`muscle_group_id`)
    REFERENCES `virtuagym`.`muscle_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `virtuagym`.`exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuagym`.`days` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day_name` VARCHAR(45) NULL,
  `plan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `plan_id_idx` (`plan_id` ASC),
  CONSTRAINT `fk_workout_day_id`
    FOREIGN KEY (`plan_id`)
    REFERENCES `virtuagym`.`workouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `virtuagym`.`workout_exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuagym`.`workout_exercises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exercise_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  `day_id` INT NOT NULL,
  `repetitions` INT NULL DEFAULT 0,
  `duration` INT NULL DEFAULT 0 COMMENT 'duration is measured in seconds',
  `weight` DECIMAL(16,1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `plan_id_idx` (`plan_id` ASC),
  INDEX `exercise_id_idx` (`exercise_id` ASC),
    INDEX `day_id_idx` (`day_id` ASC),
  CONSTRAINT `fk_ex_plan_id`
    FOREIGN KEY (`plan_id`)
    REFERENCES `virtuagym`.`workouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ex_exercise_id`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `virtuagym`.`exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ex_day_id`
    FOREIGN KEY (`day_id`)
    REFERENCES `virtuagym`.`days` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `virtuagym`.`user_workouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virtuagym`.`user_workouts` (
  `user_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `plan_id`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `virtuagym`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_id`
    FOREIGN KEY (`plan_id`)
    REFERENCES `virtuagym`.`workouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
